services:
  mysql:
    image: mysql:8.4
    container_name: tutoring_center_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "3308:3306"

    volumes:
      - tutoring_mysql_data:/var/lib/mysql

volumes:
  tutoring_mysql_data: